name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.5
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: linux-build
          path: |
            build/linux/x64/release/bundle/mumble_client