name: Test Flutter Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  test-linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.5
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build linux
  test-windows-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.5
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows